logging:
  level:
    ru:
      computel: debug

    org:
#      apache:
#        cxf:
#          services: info

      springframework:
        boot:
          context:
            embedded:
              tomcat:
                TomcatEmbeddedServletContainer: debug
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/tester??currentSchema=tester
        username: postgres
        password: admin
        type: com.zaxxer.hikari.HikariDataSource
    jpa:
        database-platform: org.hibernate.dialect.PostgresPlusDialect
        properties:
          hibernate:
            temp:
              use_jdbc_metadata_defaults: false
    liquibase:
        default-schema: tester
        change-log: classpath:db/liquibase-changelog.xml
